### ISSUE TITLE
`Set*Deadline` doesn't work well when called with zero value

### ISSUE THREAD

**Issue by fffw** [getlantern/idletiming#4]
Use int64 to represent deadline is buggy, see https://play.golang.org/p/kjQlmotLmp

Relevant code:
https://github.com/getlantern/idletiming/blob/master/idletiming_conn.go#L256
https://github.com/getlantern/idletiming/blob/master/idletiming_conn.go#L268

**Comment by myleshorton** [comment]
Great catch @fffw!
