### ISSUE TITLE
Was master force-pushed to?

### ISSUE THREAD

**Issue by fasterthanlime** [getlantern/idletiming#7]
Kind of a pointless issue, since the damage is done, but `go get -u` chokes with:

```
fatal: refusing to merge unrelated histories
```

My fault for not vendoring idletiming I guess!

**Comment by fasterthanlime** [comment]
For those finding this issue after a `go get` error message, here's how you get out of it:

```
cd $GOPATH/src/github.com/getlantern/idletiming
git fetch --all
git checkout origin/master
git branch -D master
git checkout master
```

The fetch should already be done if you got the error (but shouldn't hurt) - and there's probably a shorter way to do the last three commands, but that should get you back to the current github version of the repo.

Closing this since there's no real way for the maintainer to "fix" this.

**Comment by joesis** [comment]
Yeah sorry @fasterthanlime we broke the commit history by force pushing squashed commits. I guess removing the folder altogether and `go get` again would be simpler?
